# Generated by Django 2.1.7 on 2019-03-02 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_date', models.DateField()),
                ('drop_date', models.DateField()),
                ('dest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.DrugStock')),
            ],
        ),
        migrations.AlterField(
            model_name='supply',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.Supply'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
